version: '3.4'

services:
    myfrontend:
        image: ${DOCKER_REGISTRY-}myfrontend
        build:
            context: .
            dockerfile: MyFrontEnd/Dockerfile
        ports:
            - "51000:50001"
    myfrontend-dapr:
        image: "daprio/daprd:latest"
        command: ["./daprd", "-app-id", "MyFrontEnd", "-app-port", "80"]
        depends_on: 
            - myfrontend
        network_mode: "service:myfrontend"
    
    mybackend:
        image: ${DOCKER_REGISTRY-}mybacked
        build:
            context: .
            dockerfile: MyBackEnd/Dockerfile
    
    mybackend-dapr:
        image: "daprio/daprd:latest"
        command: ["./daprd", "-app-id", "MyBackEnd", "-app-port", "80"]
        depends_on: 
            - mybackend
        network_mode: "service:mybackend"